name = "sts2-discovery"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[[kv_namespaces]]
binding = "DISCOVERY_KV"
id = "70ab9448de16432e90a59a074a680ca0"

[triggers]
crons = ["*/10 * * * *"]
